### ISSUE TITLE
serve-handler breaks relative paths in files named index.html

### ISSUE THREAD

**Issue by pbaize** [zeit/serve-handler#19]
If you have an index.html in a subdirectory default behavior strips out the `index.html` part of the url which breaks relative paths. `public/foo/index.html` becomes `public/foo`.

This causes an issue when you have a relative script in `public/foo/index.html` referencing `<script src="main.js"></script>`. Instead of looking for `public/foo/main.js` default browser behavior is now to look for `public/main.js`.

Setting `cleanUrls` to true would fix this issue, except it causes the `public/foo/index.html` link to redirect to the directory listing for `public/foo` causing `public/foo/index.html` to be inaccessible.

If this is intended default behavior it should probably be documented, if not it would be great to have an option to serve `index.html` files.

**Comment by leo** [comment]
Feel free to add `trailingSlash` to `true`. That'll fix this! 😊

**Comment by pbaize** [comment]
thanks!

**Comment by BobLamarley** [comment]
I've opened an issue here : https://github.com/zeit/serve/issues/535 who seems very similar, but even if i add `trailingSlash` to `true`, my problem stay the same, maybe somebody has a trick ? :)
