### ISSUE TITLE
When both folder and file are present file is prefered

### ISSUE THREAD

**Issue by timneutkens** [zeit/serve-handler#35]
With the following directory structure:

```
images
 |- image1.png
 |- image2.png
 |- image3.png
images.html
```

`images.html` is preferred over `images` when going to `/images`.

I'm not sure if this is the standard behavior of other web servers.

Example of how it should probably be handled:

`/images` => `images.html` and `/images/` => `images` directory index

**Comment by leo** [comment]
In order for the folder to take precedence, you can set `cleanUrls` to `false`.

Since the package is modeled after [superstatic](https://github.com/firebase/superstatic), the default behavior, however, is that the file takes precedence and `cleanUrls` is `true`.
