### ISSUE TITLE
"unlisted" property removes the file/folder from directory list but still allows viewing them by visiting their path

### ISSUE THREAD

**Issue by afzalsayed96** [zeit/serve-handler#48]
Is this the desired behaviour? Or should attempting to traverse unlisted files/directory return 404 status.

**Comment by leo** [comment]
Yep, this is expected. The property is only meant to be used for unlisting (not showing the selected paths in the directory listing).

If you don't want the paths to be accessible, use [rewrites](https://github.com/zeit/serve-handler#rewrites-array) to a 404 page.
