### ISSUE TITLE
process.cwd not always point to main script directory

### ISSUE THREAD

**Issue by WellingGuzman** [zeit/serve-handler#49]
I do have a question, I don't know if this is a bug or an expected behavior.

When trying to run a http server that uses `serve-handler` works as expected as long as the `process.cwd()` returns the same path of the script, instead of `/`.

### Setup:
```js
await handler(request, response, {
  public: "www"
});
```
### Running script

The example below works as expected and the public path is set correctly.

https://github.com/zeit/serve-handler/blob/master/src/index.js#L508

#### Example 1:

```bash
# process.cwd() === /path/to
# public path === /path/to/www
$ node /path/to/index.js
```

I am using `forever` and it seems forever current working directory is set to `/`.

#### Example 2:

```bash
# process.cwd() === /
# public path === /www
$ forever start /path/to/index.js
```

### Result

The `serve-handler` module tries to find files in the `/www` directory instead of the correct directory `/path/to/www`.

Using absolute path doesn't fix it, as it will create an incorrect path for Example 1.

**Comment by leo** [comment]
You can now pass an absolute path: https://github.com/zeit/serve-handler/pull/50.
