### ISSUE TITLE
How do I emulate the 'serve' package -s option in serve-handler?

### ISSUE THREAD

**Issue by cstallar** [zeit/serve-handler#55]
I need serve-handler for the lower-level interface, but i need to run a react app that i built.
Any ideas on how to do this?

**Comment by leo** [comment]
Set a rewrite [like this](https://github.com/zeit/serve/blob/master/bin/serve.js#L360-L363)! 😊

**Comment by Gregoirevda** [comment]
Like [this](https://github.com/zeit/serve/blob/master/bin/serve.js#L422-L431)
