### ISSUE TITLE
Options not supported on Windows

### ISSUE THREAD

**Issue by brandon93s** [zeit/serve-handler#59]
Functionality that requires glob and/or file path matching does not work on Windows systems. The unit tests are failing, which support this. Here is a sample: 

![image](https://user-images.githubusercontent.com/4730164/45132289-5cfe1e00-b15e-11e8-82f8-5db2ea7b02e5.png)

I've experienced this not working with:
- Headers
- Rewrites
- Redirects

**Comment by compulim** [comment]
`glob-slash` is normalizing the path delimiter from `/` into `\`. And `path-to-regexp` is removing `\`.

For example, if redirect destination is set to `abc/def/index.html`, it became `abcdefindex.html`.

**Comment by compulim** [comment]
The fix is to fork `glob-slash` and change [this line](https://github.com/scottcorgan/glob-slash/blob/master/index.js#L17).

```js
return path.posix.normalize(path.posix.join('/', value));
```
