### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by afzalsayed96** [zeit/serve-handler#63]
Hi,
I've discovered a potential security flaw. Would it be okay if I open a PR for the fix or would you like it to be disclosed privately first?

**Comment by jamo** [comment]
We prefer for all security issues to be disclosed privately first:
Please send us an email to security@zeit.co with details.

If you'd like to secure the communications; you can find my pgp key 
[here](https://keybase.io/jamo)

**Comment by leo** [comment]
Fixed!
