### ISSUE TITLE
Generate ETag

### ISSUE THREAD

**Issue by mkarganov** [zeit/serve-handler#74]
Hi, we used the serve since 6.5.3 version with -c option which automatically generated ETag in the response. However in recent versions I see that this option is no longer supported.

Also I see that now it is possible to define ETag header in serve.json. 

Is there any way to generate it automatically for each server run?

**Comment by r0mflip** [comment]
If `server-handler` is required then we you can do is
``` js
const handler = require('serve-handler');
const onFinished = require('on-finished');
const etag = require('etag');

const listener = async (req, res) => {
  onFinished(res, _ => {
    // generate somehow
    res.setHeader('ETag', /* fill this */);
  });
  await handler(req, res);
};

http.createServer(listener).listen();
```

But when it comes to ETag generation I strongly recommend building a _custom_ handler, which actually, makes life a lot easier.

**Comment by mkarganov** [comment]
Hi, thank you for your response. I thought there could be smth that will work out of the box
