### ISSUE TITLE
Rewrite not working in 5.0.8

### ISSUE THREAD

**Issue by evertbouw** [zeit/serve-handler#77]
After updating serve-handler from 5.0.7 to 5.0.8 my rewrites don't seem to work. My client side routes just show 404. This also happens in https://github.com/zeit/serve with the --single option.

Minimal code:
```js
const http = require("http");
const handler = require("serve-handler");

const handlerOptions = {
    public: "./dist",
    rewrites: [{ source: "**", destination: "/index.html" }],
};

const requestListener = async (request, response) => {
    await handler(request, response, handlerOptions);
};

http.createServer(requestListener).listen(8080);

console.log(`Started webserver http://localhost:8080/`);
```

Using Windows 10, NodeJS 11.9.0

**Comment by JaminFarr** [comment]
Just about to report the same issue.

Upgraded serve to 10.1.2 -s no longer works.
Reinstalled serve@10.1.1, works fine.

Using Windows 1-, Node.js 10.14.2

**Comment by fabriziofff** [comment]
> 
> 
> Just about to report the same issue.
> 
> Upgraded serve to 10.1.2 -s no longer works.
> Reinstalled serve@10.1.1, works fine.
> 
> Using Windows 10, Node.js 10.14.2

Exactly the same!

**Comment by hgascoigne** [comment]
I am running into this issue as well. In my case, it looks like the recent security fix for paths strips the trailing slash from `requestPath` in `sourceMatches`. Ex. `/folder/` becomes `/folder` when running through `minimatch` which broke my rewrite rule which expects the trailing slash.

**Comment by Anissoft** [comment]
Btw, on Windows after `resolvedPath = path.resolve(requestPath)` ([src/index.js:24](https://github.com/zeit/serve-handler/blob/master/src/index.js)) variable resolvedPath get value like `C:\app`, so it will never match an expression `/^\/app(?:\/)?$/i`, and rewrite will never work(
