### ISSUE TITLE
Can I just use serve like a static server without file listing?

### ISSUE THREAD

**Issue by yorushika** [zeit/serve-handler#92]
Here i'm using serve like a static file server, I store files in it and visit from my program. But here comes a problem that if someone see my link such as `http://example.com/1.jpeg`, they can cut off the filename and visit `http://example.com`, then they will get **a whole list of my files**. Sometimes this will bring me some trouble.

Can I have an option to hide files from listing by visiting the root domain? I mean, when people open my domain, they will get nothing, but still they can get my files by direct link.

**Comment by Kristof-Mattei** [comment]
https://github.com/zeit/serve-handler#directorylisting-booleanarray

Set `directoryListing` to `false`.

**Comment by yorushika** [comment]
> https://github.com/zeit/serve-handler#directorylisting-booleanarray
> 
> Set `directoryListing` to `false`.

Thank you very much!
